apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaints-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complaints-postgres-deployment
  template:
    metadata:
      labels:
        app: complaints-postgres-deployment
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: complaints_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: complaints-postgres-initdb
          items:
          - key: init.sql
            path: init.sql