apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-api-deployment
  labels:
    app: note-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: note-api-deployment
  template:
    metadata:
      labels:
        app: note-api-deployment
    spec:
      containers:
        - name: note-api-deployment
          image: jatinbhatnagar/container-platform-demo-backend-notesapp-nodejs:v0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          # readinessProbe:
          #   httpGet:
          #     path: /notes/healthz
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /notes/healthz
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 20
          #   failureThreshold: 3
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
